### ISSUE TITLE
get rid of please and a

### ISSUE THREAD

**Issue by WillGardella** [atomisthq/spring-team-handlers#41]

**Comment by ddgenome** [comment]
When the bot prompts for parameters, it adds these parts. It seems like the bot constructs a message like the following:

$slackUser, please enter a *$parameter.name*, $parameter.description

So this request, and many of the others requesting the change from the comma to a period, belong in atomisthq/bot-service.

Note that our current coding guide suggests that the description for Rugs and parameters be a sentence fragment. So it will not be easy to create a sentence from that. If you want a sentence, then we may want to change our coding guidelines and all the descriptions.

It may also be better to use $parameter.displayName than $parameter.name.
