### ISSUE TITLE
fix rootPackage prompt

### ISSUE THREAD

**Issue by WillGardella** [atomisthq/spring-team-handlers#44]
There should be a period after rootPackage, `root package` should be capitalized, and the word `often` could be removed unless its important

**Comment by WillGardella** [comment]
Sorry, I'm being ungrammatical - if we make a second sentence by capitalizing Root, that sentence also needs a verb.

**Comment by ddgenome** [comment]
The often is important and the changing of the structure of the prompt has to be done in the bot, see #41 .
