### ISSUE TITLE
fix enable travis build wording

### ISSUE THREAD

**Issue by WillGardella** [atomisthq/spring-team-handlers#47]
This is worded like a directed flow, suggesting that the user has to do five things, but it really just completes the steps itself and the user has to accept the PR. I would prefer if we put more emphasis on the step we do need them to complete upfront, which is accepting the PR. Please replace the numbers with check marks, and just put an ellipses at the end of the lines that are currently numbered. Altogether, it looks like this:

Creating a PR to enable Travis build... 
✓ Enabled build for **demo1** on Travis CI...
✓ Encrypted GitHub token for Travis CI...
✓ Encrypted Artifactory token for Travis CI...
✓ Encrypted Artifactory user for Travis CI...
✓ Added Travis build files to the repo...
Done! [Accept my PR to enable the Travis build](http://www.example.com/pr)

**Comment by ddgenome** [comment]
The link to the PR will appear in the lifecycle message that appears for the PR. We will not have the PR link at the time the last message is created. Does it have to be a link?

**Comment by ddgenome** [comment]
Do you really want ellipses at the end of every line? Seems like we could get away with just having them on the first line.

**Comment by ddgenome** [comment]
You really don't like the bot to be polite, do you?

**Comment by jessitron** [comment]
but then the user (or demo-watcher) won't know how many steps there are.

Can we have a status bar that fills up as it goes so we can tell we're close?

^ I'm not serious (unless you know how to do this easily in which case serious)

**Comment by ddgenome** [comment]
I am going to change "Accept my PR to enable the Travis build" to "Accept my PR to merge the changes in to `master`." since technically we have already enabled the Travis CI build for the repo.

**Comment by ddgenome** [comment]
I could do a simple progress bar.

**Comment by ddgenome** [comment]
What about this?

Creating a PR to enable Travis build…
`[✓----]` Enabled build for ${repoUrl} on Travis CI…
`[✓✓---]` Encrypted GitHub token for Travis CI…
`[✓✓✓--]` Encrypted Maven password for Travis CI…
`[✓✓✓✓-]` Encrypted Maven user for Travis CI…
`[✓✓✓✓✓]` Added Travis build files to the repository…
Done! Accept my PR to merge the changes in to `master`.
