### ISSUE TITLE
fix wording of rollout changes message

### ISSUE THREAD

**Issue by WillGardella** [atomisthq/spring-team-handlers#49]
I don't completely understand what's happening with this command, so some discussion might be needed. The message that the seed has changed comes to the general channel, which we must do because we don't know how many projects might be following it. So perhaps it might be cleaner to report what was detected (Changes to features in `spring-rest-seed` detected: _Create logback.xml_. What do you want to do?), then have two buttons "Roll out change to followers?" "Ignore".

**Comment by WillGardella** [comment]
I don't completely understand what's happening with this command, so some discussion might be needed. The message that the seed has changed comes to the general channel, which we must do because we don't know how many projects might be following it. So perhaps it might be cleaner to report what was detected (Changes to features in `spring-rest-seed` detected: _Create logback.xml_.  What do you want to do?), then have two buttons "Roll out change to followers?" "Ignore".

**Comment by ddgenome** [comment]
Are you talking about these messages?

<img width="518" alt="cascade-double-backticks" src="https://user-images.githubusercontent.com/57881/27090260-5730d9b6-5022-11e7-909d-8bb3c6c37d07.png">

**Comment by ddgenome** [comment]
Here's an example of the current text:

<img width="1038" alt="changes-detected-message" src="https://user-images.githubusercontent.com/57881/27090352-9e3417c4-5022-11e7-8e2a-656c1dc131cc.png">

**Comment by ddgenome** [comment]
I'm reluctant to add an "Ignore" button that does nothing.

**Comment by cdupuis** [comment]
Hmm, why couldn't `ignore` just re-write the message and remove it from slack?

**Comment by ddgenome** [comment]
Once all your rewrite stuff is in production, it can.

**Comment by ddgenome** [comment]
What is looks like now:

<img width="512" alt="cascade-confirmation" src="https://user-images.githubusercontent.com/57881/27101679-57679476-5048-11e7-9962-c35d4a248559.png">
