### ISSUE TITLE
Use SNAPSHOT builds in seeds/generated projects

### ISSUE THREAD

**Issue by ddgenome** [atomisthq/spring-team-handlers#56]
To enable demo flow, enable -SNAPSHOT versions/builds/deploys in the spring-rest-seed and java-lib-seed projects.

This will require creating a snapshot repository in Artifactory.

**Comment by ddgenome** [comment]
libs-snapshot-local already exists on atomist.jfrog.io

**Comment by cdupuis** [comment]
can we make that a different repo for demo projects?

**Comment by ddgenome** [comment]
We could, although we do not currently use the snapshot repo for anything. You do need a repository section in the distributionManagement section, so we should probably create a demo version for that, so may as well do the same for snapshot.
